alias dev='cd ~/Develop'
alias ..='cd ..'
alias ...='cd ../..'

alias n='npm'
alias ni='npm install'
alias nd='npm run dev'
alias nb='npm run build'

alias y='yarn'
alias yd='yarn dev'
alias ys='yarn storybook'
alias yt='yarn test:unil'
alias yb='yarn build'
alias yp='yarn preview'

alias g='git'
alias gst='git status'
alias gb='git branch'
alias gbm='git branch -m'
alias ga='git add .'
alias gc='git commit'
alias gac='git add . && git commit'
alias gca='git commit --amend'
alias gco='git checkout'
alias gcob='git checkout -b'
alias gsw='git switch'
alias gswc='git switch -c'
alias glog='git log'
alias gpm='git pull origin main'
alias grh='git reset --hard HEAD'
alias grao='git remote add origin'
alias gcl='git clone'

alias d='docker'
alias dps='docker ps'
alias dpsa='docker ps -a'
alias di='docker images'
alias drd='docker run -d'
alias dre='docker run exec -it'
alias dc='docker compose'
alias dcu='docker compose up'

alias v='code'
alias sz='source ~/.zshrc'
alias vz='vi ~/.zshrc'